// -----------------------------------------------------------------------
// <autogenerated>
//  This code was generated by Aashish Koirala's Text Templating Library.
//  Do not make changes to this code as they will be lost.
// </autogenerated>
// -----------------------------------------------------------------------

using System;
using System.ComponentModel.Composition;
using AK.Commons.DataAccess;
using AK.FinanceManager.Contracts.DataAccess.Entities;
using AK.FinanceManager.Contracts.DataAccess.Repositories;

namespace AK.FinanceManager.DataAccess.Repositories
{
    [Export(typeof(IAppUserRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class AppUserRepository : RepositoryBase<AppUser, int>, IAppUserRepository { }
    [Export(typeof(IWorkbookRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class WorkbookRepository : RepositoryBase<Workbook, int>, IWorkbookRepository { }
    [Export(typeof(IAppUserWorkbookRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class AppUserWorkbookRepository : RepositoryBase<AppUserWorkbook, int>, IAppUserWorkbookRepository { }
    [Export(typeof(IFinanceTransactionRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class FinanceTransactionRepository : RepositoryBase<FinanceTransaction, int>, IFinanceTransactionRepository { }
    [Export(typeof(IVendorRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class VendorRepository : RepositoryBase<Vendor, int>, IVendorRepository { }
    [Export(typeof(IBudgetHeadingRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class BudgetHeadingRepository : RepositoryBase<BudgetHeading, int>, IBudgetHeadingRepository { }
    [Export(typeof(IVendorBudgetHeadingRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class VendorBudgetHeadingRepository : RepositoryBase<VendorBudgetHeading, int>, IVendorBudgetHeadingRepository { }
    [Export(typeof(IBudgetHeadingTypeRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class BudgetHeadingTypeRepository : RepositoryBase<BudgetHeadingType, int>, IBudgetHeadingTypeRepository { }
    [Export(typeof(IVendorMappingRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class VendorMappingRepository : RepositoryBase<VendorMapping, int>, IVendorMappingRepository { }
    [Export(typeof(IBudgetRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class BudgetRepository : RepositoryBase<Budget, int>, IBudgetRepository { }
    [Export(typeof(IBudgetItemRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class BudgetItemRepository : RepositoryBase<BudgetItem, int>, IBudgetItemRepository { }
}