// -----------------------------------------------------------------------
// <autogenerated>
//  This code was generated by Aashish Koirala's Text Templating Library.
//  Do not make changes to this code as they will be lost.
// </autogenerated>
// -----------------------------------------------------------------------

using System;
namespace AK.FinanceManager.Contracts.DataAccess.Entities
{
    public partial class AppUser
    {
        public virtual int Id { get; set; }
        public virtual string UserName { get; set; }
        public virtual System.Collections.Generic.IList<Workbook> WorkbookList { get; set; }
    }

    public partial class Workbook
    {
        public virtual int Id { get; set; }
        public virtual string Name { get; set; }
        public virtual System.Collections.Generic.IList<FinanceTransaction> FinanceTransactionList { get; set; }
        public virtual System.Collections.Generic.IList<Vendor> VendorList { get; set; }
        public virtual System.Collections.Generic.IList<BudgetHeadingType> BudgetHeadingTypeList { get; set; }
        public virtual System.Collections.Generic.IList<Budget> BudgetList { get; set; }
    }

    public partial class AppUserWorkbook
    {
        public virtual int Id { get; set; }
        public virtual AppUser AppUser { get; set; }
        public virtual Workbook Workbook { get; set; }
    }

    public partial class FinanceTransaction
    {
        public virtual int Id { get; set; }
        public virtual Workbook Workbook { get; set; }
        public virtual DateTime TransactionDate { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual BudgetHeading BudgetHeading { get; set; }
        public virtual decimal Amount { get; set; }
        public virtual string Notes { get; set; }
    }

    public partial class Vendor
    {
        public virtual int Id { get; set; }
        public virtual Workbook Workbook { get; set; }
        public virtual string Name { get; set; }
        public virtual System.Collections.Generic.IList<VendorBudgetHeading> VendorBudgetHeadingList { get; set; }
        public virtual System.Collections.Generic.IList<VendorMapping> VendorMappingList { get; set; }
    }

    public partial class BudgetHeading
    {
        public virtual int Id { get; set; }
        public virtual string Name { get; set; }
        public virtual BudgetHeadingType BudgetHeadingType { get; set; }
        public virtual bool IsAnnualized { get; set; }
        public virtual bool IsBeginningSurplus { get; set; }
        public virtual bool IsEndingSurplus { get; set; }
    }

    public partial class VendorBudgetHeading
    {
        public virtual int Id { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual BudgetHeading BudgetHeading { get; set; }
        public virtual bool IsDefault { get; set; }
    }

    public partial class BudgetHeadingType
    {
        public virtual int Id { get; set; }
        public virtual Workbook Workbook { get; set; }
        public virtual string Name { get; set; }
        public virtual bool IsMoneyComingIn { get; set; }
        public virtual System.Collections.Generic.IList<BudgetHeading> BudgetHeadingList { get; set; }
    }

    public partial class VendorMapping
    {
        public virtual int Id { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual string MappedName { get; set; }
    }

    public partial class Budget
    {
        public virtual int Id { get; set; }
        public virtual Workbook Workbook { get; set; }
        public virtual DateTime PeriodStartDate { get; set; }
        public virtual DateTime PeriodEndDate { get; set; }
        public virtual System.Collections.Generic.IList<BudgetItem> BudgetItemList { get; set; }
    }

    public partial class BudgetItem
    {
        public virtual int Id { get; set; }
        public virtual Budget Budget { get; set; }
        public virtual BudgetHeading BudgetHeading { get; set; }
        public virtual decimal Amount { get; set; }
    }

}
