// -----------------------------------------------------------------------
// <autogenerated>
//  This code was generated by Aashish Koirala's Text Templating Library.
//  Do not make changes to this code as they will be lost.
// </autogenerated>
// -----------------------------------------------------------------------

using System;
using AK.Commons.DataAccess;
using AK.FinanceManager.Contracts.DataAccess.Entities;

namespace AK.FinanceManager.Contracts.DataAccess.Repositories
{
    public partial interface IAppUserRepository : IRepository<AppUser, int> { }
    public partial interface IWorkbookRepository : IRepository<Workbook, int> { }
    public partial interface IAppUserWorkbookRepository : IRepository<AppUserWorkbook, int> { }
    public partial interface IFinanceTransactionRepository : IRepository<FinanceTransaction, int> { }
    public partial interface IVendorRepository : IRepository<Vendor, int> { }
    public partial interface IBudgetHeadingRepository : IRepository<BudgetHeading, int> { }
    public partial interface IVendorBudgetHeadingRepository : IRepository<VendorBudgetHeading, int> { }
    public partial interface IBudgetHeadingTypeRepository : IRepository<BudgetHeadingType, int> { }
    public partial interface IVendorMappingRepository : IRepository<VendorMapping, int> { }
    public partial interface IBudgetRepository : IRepository<Budget, int> { }
    public partial interface IBudgetItemRepository : IRepository<BudgetItem, int> { }
}
